### ISSUE TITLE
[QUESTION] impact of Lambda Layers on performance

### ISSUE THREAD

**Issue by sebsto** [JeremieRodon/demo-rust-lambda#1]
Hello, this is a question and not an issue.

I noticed you used Lambda layers for python but not for Rust.
Do you think this can impact performance one way or the other ? What is the impact on cold start ? And subsequent runs ?
According to articles and blog posts I read, Layers do not seem to have an impact on performance, not even cold start.

Do you confirm  you  observed the same?

**Comment by JeremieRodon** [comment]
Hello!
As of now, I did not compare the performances of Python lambdas with and without layers.

I believe it does not have any significant impact: when a container/microVM is launched by Lambda (cold start) it needs to retrieve the sources no matter what. Having (e.g.) 1MB in the main archive, or 100KB in the main archive + 900KB in a layer, should not change anything. We could argue that 2 separate archives are less efficiently compressed than a single one, or that maybe having 2 parallel downloads instead of a single one is longer, but I doubt the difference it makes, if any, is measurable.
Beyond the cold-start, all the Python imports have already been done: they are loaded in memory and their file-system origins should not be relevant anymore.
That being said, I should probably put this hypothesis to test...

For Rust lambdas, we use compiled binaries on a custom runtime, so layers are out of scope (I suppose?).

**Comment by sebsto** [comment]
Merci Jeremie.
I think it makes sense.

FYI - you can use layers with a custom runtime. The layer content must be in `/bin` and `/lib`. But I don't think it's worth the trouble for your Rust example.
